# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('age', models.IntegerField(verbose_name='\u5e74\u7eaa')),
                ('image', models.ImageField(upload_to='static/images')),
            ],
            options={
                'verbose_name': '\u5185\u5bb9\u7ba1\u7406',
                'verbose_name_plural': '\u5185\u5bb9\u7ba1\u7406',
            },
        ),
    ]
